/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimpleStopwatchPanel.java
 *
 * Created on 2013-maj-09, 10:36:58
 */

package org.catacombae.simpletimer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author erik
 */
public class SimpleStopwatchPanel extends javax.swing.JPanel {

    public interface Controller {
        public void startStopButtonActionPerformed(SimpleStopwatchPanel p);
    }

    /** Creates new form SimpleStopwatchPanel */
    public SimpleStopwatchPanel(final Controller c) {
        initComponents();

        startButton.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                c.startStopButtonActionPerformed(SimpleStopwatchPanel.this);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        messageAreaScroller = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        startButtonPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(337, 241));

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Stopwatch stopped");

        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("0.0 seconds");

        messageArea.setColumns(20);
        messageArea.setRows(5);
        messageAreaScroller.setViewportView(messageArea);

        startButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        startButton.setText("Start");
        startButtonPanel.add(startButton);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, startButtonPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, messageAreaScroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, statusLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, timeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(statusLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(timeLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(messageAreaScroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(startButtonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea messageArea;
    private javax.swing.JScrollPane messageAreaScroller;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel startButtonPanel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    public void setRunning(boolean isRunning) {
        if(isRunning) {
            startButton.setText("Stop");
            statusLabel.setText("Stopwatch running");
        }
        else {
            startButton.setText("Start");
            statusLabel.setText("Stopwatch stopped");
        }
    }

    public void setTimeLabelText(String text) {
        timeLabel.setText(text);
    }
}
