/*
 * SimpleTimerPanel3.java
 *
 * Created on den 18 juni 2008, 14:37
 */

package org.catacombae.simpletimer;

import java.awt.event.ActionListener;

/**
 *
 * @author  Erik
 */
public class SimpleTimerPanel extends javax.swing.JPanel {

    /** Creates new form SimpleTimerPanel3 */
    public SimpleTimerPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        hoursLabel = new javax.swing.JLabel();
        hoursField = new javax.swing.JTextField();
        minutesLabel = new javax.swing.JLabel();
        minutesField = new javax.swing.JTextField();
        secondsLabel = new javax.swing.JLabel();
        secondsField = new javax.swing.JTextField();
        controlButtonPanel = new javax.swing.JPanel();
        controlButton = new javax.swing.JButton();

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Timer stopped");

        hoursLabel.setText("Hours:");

        hoursField.setColumns(4);
        hoursField.setText("0");

        minutesLabel.setText("Minutes:");

        minutesField.setColumns(2);
        minutesField.setText("0");

        secondsLabel.setText("Seconds:");

        secondsField.setColumns(2);
        secondsField.setText("0");

        controlButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        controlButton.setText("Start");
        controlButtonPanel.add(controlButton);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(statusLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(hoursLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(hoursField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(minutesLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(minutesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(secondsLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(secondsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(controlButtonPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(statusLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(hoursLabel)
                    .add(hoursField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(minutesLabel)
                    .add(minutesField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(secondsLabel)
                    .add(secondsField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(controlButtonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void addControlButtonListener(ActionListener listener) {
        controlButton.addActionListener(listener);
    }
    public String getHoursFieldText() { return hoursField.getText(); }
    public String getMinutesFieldText() { return minutesField.getText(); }
    public String getSecondsFieldText() { return secondsField.getText(); }
    
    // <setters>
    
    public void setStatusLabelText(String s) { statusLabel.setText(s); }
    public void setHoursFieldText(String s) { hoursField.setText(s); }
    public void setMinutesFieldText(String s) { minutesField.setText(s); }
    public void setSecondsFieldText(String s) { secondsField.setText(s); }
    public void setControlButtonText(String s) { controlButton.setText(s); }
    public void setHoursFieldEnabled(boolean b) { hoursField.setEnabled(b); }
    public void setMinutesFieldEnabled(boolean b) { minutesField.setEnabled(b); }
    public void setSecondsFieldEnabled(boolean b) { secondsField.setEnabled(b); }
    //public void setEnabled(boolean b) { .setEnabled(b); }
    public void setControlButtonEnabled(boolean b) { controlButton.setEnabled(b); }
    
    // </setters>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton controlButton;
    private javax.swing.JPanel controlButtonPanel;
    private javax.swing.JTextField hoursField;
    private javax.swing.JLabel hoursLabel;
    private javax.swing.JTextField minutesField;
    private javax.swing.JLabel minutesLabel;
    private javax.swing.JTextField secondsField;
    private javax.swing.JLabel secondsLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

}
